name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Qt
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip
        pip3 install aqtinstall
        aqt install-qt linux desktop 5.15.2 gcc_64

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y qtbase5-dev qt5-qmake

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'  # حدد إصدار Python المطلوب

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip

    - name: Build project
      run: |
        qmake project.pro
        make
    
        

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to server
      run: |
        echo "Deploying application..."  # Add your deployment script/commands here
